# Generated by Django 4.1.3 on 2024-06-07 17:31

import autoslug.fields
from django.db import migrations, models
import django_ckeditor_5.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=50, null=True)),
                ('Mobile', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=10)),
                ('Form_Type', models.CharField(max_length=50, null=True)),
                ('Target_Url', models.CharField(max_length=1000, null=True)),
                ('Is_Done', models.BooleanField(default=False, null=True)),
                ('Created_At', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Addmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', tinymce.models.HTMLField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=50, null=True)),
                ('Mobile', models.CharField(max_length=50, null=True)),
                ('District', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=10, null=True)),
                ('Form_Type', models.CharField(max_length=50, null=True)),
                ('Target_Url', models.CharField(max_length=1000, null=True)),
                ('Is_Done', models.BooleanField(default=False, null=True)),
                ('Created_At', models.DateTimeField(auto_now=True)),
                ('Payment_Recieved', models.BooleanField(default=False, null=True)),
                ('Amount', models.CharField(max_length=50, null=True)),
                ('Payment_Mode', models.CharField(max_length=50, null=True)),
                ('Transaction_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bihar_Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Central_Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_nfs', models.CharField(max_length=50)),
                ('Email_nfs', models.EmailField(max_length=254, unique=True)),
                ('Message_nfs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('link', models.URLField(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('link', models.URLField(null=True)),
                ('upload', models.FileField(null=True, upload_to='uploads/')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=50)),
                ('two', models.CharField(max_length=50)),
                ('titi', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='one', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user_District', models.CharField(max_length=25, unique=True)),
                ('State', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
