# Generated by Django 4.1.3 on 2024-06-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0002_application_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Assign_To',
        ),
    ]
