# Generated by Django 4.1.3 on 2024-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0003_remove_application_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Assign_To',
            field=models.CharField(choices=[('G', 'Gopalganj'), ('S', 'Siwan'), ('P', 'Patna'), ('C', 'Champaran'), ('M', 'Motihari'), ('CH', 'Chhapra'), ('A', 'Aurangabad'), ('G', 'Gaya'), ('A', 'Sasaram')], default='G', max_length=15),
        ),
    ]
