# Generated by Django 4.1.3 on 2024-06-07 18:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0004_application_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmision',
            name='Discription',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
