# Generated by Django 4.1.3 on 2024-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0005_alter_addmision_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted_form',
            name='Is_Application_Initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted_form',
            name='Is_Form_Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accepted_form',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
