# Generated by Django 4.1.3 on 2024-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0006_accepted_form_is_application_initiated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted_form',
            name='Is_Application_Initiated',
        ),
        migrations.RemoveField(
            model_name='accepted_form',
            name='Is_Form_Completed',
        ),
        migrations.RemoveField(
            model_name='accepted_form',
            name='Remarks',
        ),
        migrations.AddField(
            model_name='application',
            name='Is_Application_Initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='Is_Form_Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
