# Generated by Django 5.0.6 on 2024-06-11 11:22

import autoslug.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0008_remove_latest_job_link_remove_latest_job_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passport_DL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rtps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
    ]
