# Generated by Django 5.0.6 on 2024-06-11 18:51

import autoslug.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0009_farmers_passport_dl_rtps_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=100, null=True)),
                ('Post_Name', models.CharField(max_length=100, null=True)),
                ('Post_Date', models.DateTimeField(null=True)),
                ('Short_Info', models.TextField(max_length=1000, null=True)),
                ('Discription', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('Cotegory', models.CharField(choices=[('R', 'RTPS'), ('M', 'Mutation/Lagaan'), ('S', 'Scholarship'), ('A', 'Anudan'), ('P', 'Passport/DL'), ('F', 'Farmers'), ('P', 'Pan Card')], default='Select', max_length=15)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Post_Name', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Accepted_Form',
        ),
        migrations.DeleteModel(
            name='Farmers',
        ),
        migrations.DeleteModel(
            name='name',
        ),
        migrations.DeleteModel(
            name='Passport_DL',
        ),
        migrations.DeleteModel(
            name='Rtps',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
