# Generated by Django 5.0.6 on 2024-06-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0010_multi_post_delete_accepted_form_delete_farmers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multi_post',
            old_name='Cotegory',
            new_name='Category',
        ),
    ]
