# Generated by Django 5.0.6 on 2024-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0011_rename_cotegory_multi_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Is_Application_Initiated',
            new_name='Completed',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Is_Form_Completed',
            new_name='Initiated',
        ),
        migrations.AlterField(
            model_name='multi_post',
            name='Category',
            field=models.CharField(choices=[('R', 'RTPS'), ('M', 'Mutation/Lagaan'), ('S', 'Scholarship'), ('A', 'Anudan'), ('P', 'Passport/DL'), ('F', 'Farmers'), ('P', 'Pan Card')], default='R', max_length=15),
        ),
    ]
