# Generated by Django 5.0.6 on 2024-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0012_rename_is_application_initiated_application_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Assign_To',
            field=models.CharField(choices=[('G', 'Gopalganj'), ('S', 'Siwan'), ('P', 'Patna'), ('C', 'Champaran'), ('M', 'Motihari'), ('CH', 'Chhapra'), ('A', 'Aurangabad'), ('G', 'Gaya'), ('A', 'Sasaram')], default='G', max_length=15),
        ),
        migrations.AlterField(
            model_name='multi_post',
            name='Category',
            field=models.CharField(choices=[('RTPS', 'RTPS'), ('Mutation/Lagaan', 'Mutation/Lagaan'), ('Scholarship', 'Scholarship'), ('Anudan', 'Anudan'), ('Passport/DL', 'Passport/DL'), ('Farmers', 'Farmers'), ('Pan Card', 'Pan Card')], default='RTPS', max_length=15),
        ),
    ]
