# Generated by Django 5.0.6 on 2024-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0014_alter_application_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Assign_To',
            field=models.CharField(choices=[('Gopalganj', 'Gopalganj'), ('Siwan', 'Siwan'), ('Patna', 'Patna'), ('Champaran', 'Champaran'), ('Motihari', 'Motihari'), ('Chhapra', 'Chhapra'), ('Aurangabad', 'Aurangabad'), ('Gaya', 'Gaya'), ('Sasaram', 'Sasaram')], default='Gopalganj', max_length=15),
        ),
    ]
