# Generated by Django 5.0.6 on 2024-06-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0015_alter_customuser_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_District',
        ),
    ]
