# Generated by Django 5.0.6 on 2024-06-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0016_remove_customuser_user_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Father', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=60)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bihar_Scheme',
            new_name='Admit_Card',
        ),
        migrations.RenameModel(
            old_name='Central_Scheme',
            new_name='Govt_Scheme',
        ),
    ]
