# Generated by Django 5.0.6 on 2024-06-19 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0017_partner_registration_rename_bihar_scheme_admit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmision',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='admit_card',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='govt_scheme',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='latest_job',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='multi_post',
            name='Discription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
