# Generated by Django 5.0.6 on 2024-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0018_alter_addmision_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_registration',
            name='Remark',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
