# Generated by Django 5.0.6 on 2024-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0020_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmision',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addmision',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addmision',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='govt_scheme',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='govt_scheme',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='govt_scheme',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incentive',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='latest_job',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='latest_job',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='latest_job',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='multi_post',
            name='Payment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='multi_post',
            name='ServiceCharge',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='multi_post',
            name='SupportingDoc',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
