# Generated by Django 5.0.6 on 2024-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0021_addmision_payment_addmision_servicecharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
