# Generated by Django 5.0.6 on 2024-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0022_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_job',
            name='Payment_Link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
