# Generated by Django 5.0.6 on 2024-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0023_latest_job_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='govt_scheme',
            name='Payment_Link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
