# Generated by Django 5.0.6 on 2024-08-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfs', '0024_govt_scheme_payment_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappmessage',
            old_name='sender',
            new_name='from_number',
        ),
    ]
